-# Configuration for Label Actions-remove label id:-# more information needed:discussions:-# Remove labels unlabel:-#'more information needed'inbacklog:discussions:unlabel:-'in backlog'fixed:discussions:unlabel:-'fixed'
